[[redirects]]
  # Redirect default Netlify subdomain to primary domain
  from = "https://kitos.netlify.com/*"
  to = "https://nikitakirsanov.com/:splat"

[[redirects]]
  from = "/game-of-life/"
  to = "https://kitos.github.io/game-of-life/"
  status = 200
