name: Check Vabali
on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  check_vabali:
    runs-on: ubuntu-latest
    steps:
      - name: check vabali
        uses: denoland/setup-deno@v1.1.1
      
      - run: |
          deno run --allow-net=vabaliwellness.km-it.de:44301 \
          --allow-run https://gist.githubusercontent.com/kitos/c0fffcf09579744f7c00fad897fdbff0/raw/2cedd00e5eb795b444b71b40ddb9ff72f418819e/Vabali.ts

      - name: notify me
        uses: denoland/setup-deno@v1.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Yo, hello